name: Deploy Django to AWS EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /usr/COEN_6311_project_travel
          git reset --hard
          git pull
          sudo pkill -f 'python manage.py start_order_consumer'
          killall -s INT uwsgi
          killall -s INT celery
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          uwsgi --ini uwsgi.ini
          nohup python manage.py start_order_consumer > start_order_consumer.log 2>&1 &
          nohup celery -A COEN_6311_project_travel worker -l info -f logs/celery_worker.log -P threads > celery_worker.log 2>&1 &
          nohup celery -A COEN_6311_project_travel beat -l info -f logs/celery_beat.log > celery_beat.log 2>&1 &



